version: "3"

services:
  db:
    image: mariadb:11
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
    restart: always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"