spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, verification, swagger, actuator"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://tikichat_db:3306/security?serverTimezone=Asia/Seoul
    username: ${DB_ID}
    password: ${DB_PW}

  jpa:
    open-in-view: false
#    show-sql: true
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
    hibernate:
      ddl-auto: create

  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucketName: ${AWS_S3_BUCKET}
