jwt:
  secretKey: ${JWT_SECRET_KEY}

  access:
#    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    expiration: 60000 # 1분
    header: Authorization

  refresh:
#    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    expiration: 300000 # 5분
    header: Authorization-refresh