spring:
  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

#  h2:
#    console:
#      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create
