spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, verification, swagger"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    open-in-view: false
#    show-sql: true
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
    hibernate:
      ddl-auto: create
