name: cd
on:
  pull_request:
    types: [ closed ]
    branches: [ master ]
    # paths: 
    # - 'src/**'

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Create mainkey.pem from secrets
        run: |
          echo "${{ secrets.MAINKEY_PEM }}" > mainkey.pem
          chmod 600 mainkey.pem

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ec2-54-253-245-207.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH to EC2 instance
        run: |
          ssh -i mainkey.pem ubuntu@ec2-54-253-245-207.ap-southeast-2.compute.amazonaws.com << 'EOF'
            ls -al
            ls ${{ github.sha }}
          EOF
        # sed -i "/tikichat_server:/,/image: /s|image: .*|image: dydydade/tikichat-server:${{ github.sha }}|g" docker-compose.yml
        # docker-compose down
        # sudo rm -r master_db
        # docker-compose up -d
          
      - name: Remove mainkey.pem
        run: rm mainkey.pem


