name: cicd-1
on:
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ master ]
    # paths: 
    # - 'src/**'

jobs:
  image-build:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v4

    - name: login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: docker build
      run: |
        docker build -f Dockerfile --tag ${{ secrets.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.sha }}

  image-run-test:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    needs: [ image-build ]
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v4
    - name: login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: update docker-compose.yml
      run: |
        sed -i "/tikichat_server:/,/image: /s|image: .*|image: ${{ vars.REPOSITORY }}:${{ github.sha }}|g" docker-compose.yml
    - name: docker-compose up
      run: |
        docker-compose up
    - name: dummy test
      run: |
        echo "test done"

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Create .ssh directory
        run: mkdir -p ~/.ssh

      - name: Create mainkey.pem from secrets
        run: |
          echo "${{ secrets.MAINKEY_PEM }}" > mainkey.pem
          chmod 600 mainkey.pem

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ec2-54-253-245-207.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: SSH to EC2 instance
        # env:
        #   DOCKER_IMAGE_TAG: ${{ github.sha }}
        run: |
          ssh -i mainkey.pem ubuntu@ec2-54-253-245-207.ap-southeast-2.compute.amazonaws.com << 'EOF'
            ls -al
          EOF
        # sed -i "/tikichat_server:/,/image: /s|image: .*|image: dydydade/tikichat-server:${DOCKER_IMAGE_TAG}|g" docker-compose.yml
        # docker-compose down
        # sudo rm -r master_db
        # docker-compose up -d
          
      - name: Remove mainkey.pem
        run: rm mainkey.pem


